### ISSUE TITLE
app/assets is stripped from path, but is included anyway

### ISSUE THREAD

**Issue by BrianHicks** [mllrsohn/sprite-brunch#8] opened 2015-11-11 22:35 UTC
So it looks like the default for this package is `app/assets/images/sprites`. In the current versions of Brunch, `app/assets` will be stripped from the path in the public folder, but the generated stylesheets (I'm using scss) still have the `app/assets` in them. This makes invalid links.

Am I missing something to configure for this, or is it a bug?

**Comment by delitamakanda** [comment] 2015-11-14 14:55
nope. not a bug sorry. I must reconfigure the gitignore files to have assets files.

**Comment by aedryan** [comment] 2017-01-19 15:51
This should be fixed by the new destSprites config property that allows you to specify where your sprite files are dumped.  You can dump them somewhere in your public directory or somewhere in your app/assets directory and it will take that into account when making paths to those sprite files in the stylesheet.

**Closed by aedryan** 2017-01-19 15:51 UTC
